### ISSUE TITLE
"CT" space isn't computing with the right hierarchy

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-confluence-migrator#52] opened 2021-11-19 11:22 UTC
Steps to reproduce:

1. Follow the Confluence Migrator steps 1 to 4 using the [CT space](https://xwikisas.atlassian.net/wiki/spaces/CT/overview?homepageId=21987463) 
2. Import the CT pages exported https://up1.xwikisas.com/#9llAln4P4UorYHrsvOOYCg
3. Follow the other instructions till step 6
4. Click on "Compute plan"

Expected results: The Hierarchy from the CT space in Confluence is shown under "Plan"

Actual results: "There is nothing to do!"
![Hierarchy](https://user-images.githubusercontent.com/40691112/142614467-3f97d1c6-947a-4822-b7ed-5b7a65959332.jpg)

Environments: Windows 10, XWiki 13.4.5 with MySQL 8.0 and Chrome 95, com.xwiki.confluence:application-confluence-migrator-ui version:1.0-rc-10

**Comment by acotiuga** [comment] 2021-12-02 19:21
@ane-gabriela is there any JS error in the browser tools console? 
I was not able to reproduce the issue and the `There is nothing to do!` info message is an intermediary feedback that precedes the actual plan result, which is loading all the time for me.
Thanks!

**Comment by acotiuga** [comment] 2021-12-03 18:42
https://jira.xwiki.org/browse/XWIKI-19204 was fixed in platform, to address the Annotations JS code error.

**Comment by snazare** [comment] 2022-10-25 21:27
closing this as the issue does not reproduce anymore

**Closed by snazare** 2022-10-25 21:27 UTC
Labels: Priority: Blocker, Type: Bug
