### ISSUE TITLE
Links to pages with forward slash "/" break during import

### ISSUE THREAD

**Issue by fknorn** [xwikisas/application-confluence-migrator#89] opened 2022-11-17 08:59 UTC
It appears that links to pages with a slash in the title are not updated properly during migration and then are broken, i.e. pointing to an inexistent page. But the page exists, just under a different title, as the slash gets ... well ... slashed. (Sorry, pun could not be avoided.)

### Steps to reproduce

1. On Confluence, create a page with a slash in the title
2. Link to it from another page
3. Export ... migrate ...
4. The link will be broken, since the migrator removes the slash from the title/url, but the link itself still points to the page with the slash in it.

### Versions

- Confluence Server edition, v7.18.3
- XWiki Debian 14.9
- Confluence Migrator 1.0.8
- Nested Pages Migrator Application 0.9.0

### Screenshots

![Screenshot 2022-11-17 at 09 47 48](https://user-images.githubusercontent.com/4229411/202401492-1e59bc75-0300-4dcd-8335-c5857896360a.png)

![Screenshot 2022-11-17 at 09 47 03](https://user-images.githubusercontent.com/4229411/202401479-5c519c9a-d9cb-4926-9a89-0417c14bbe24.png)

![Screenshot 2022-11-17 at 09 45 45](https://user-images.githubusercontent.com/4229411/202401488-56c5febe-8e32-40eb-afe2-e5cdda449788.png)

![Screenshot 2022-11-17 at 09 50 01](https://user-images.githubusercontent.com/4229411/202401494-ae480a36-03f4-4331-a013-2aef0bef49d6.png)

**Comment by snazare** [comment] 2022-11-17 09:02
hi @fknorn could you please let us know if this seems to be the same issue as #88  ?

**Comment by fknorn** [comment] 2022-11-17 09:29
> hi @fknorn could you please let us know if this seems to be the same issue as #88 ?

Can't say, but I don't believe so. This is not about the page being moved here or there, this is about on the one hand the slash being zapped in the page's _url_, but then on the other hand any _links_ pointing to that page not being updated  (there, there slash is not removed, so they get disconnected, compare second and forth screenshot).

**Comment by snazare** [comment] 2023-02-15 19:34
An XWiki architect was able to reproduce the issue on a local 14.10.3 instance with Confluence migrator 1.0.9 and 1.0.10. We are investigating the issue and will propose a fix asap.

**Comment by snazare** [comment] 2023-03-01 19:25
We were able to isolate the issue. In short, the SOLR index is indexing pages too quickly after import, before the Nested Pages migrator takes effect on all pages. Therefore some links are converted and some are not, making this issue reproduce sporadically. We are working on a fix which will be deployed very soon in the next version of the migrator.

**Comment by snazare** [comment] 2023-03-02 20:25
Fixed in version 1.0.11 of the Confluence Migrator.

**Closed** 2023-03-02 20:24 UTC
Labels: Priority: Critical, Type: Bug
